name: build ebook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: sudo apt update
      - run: sudo apt install calibre-bin
      - run: sudo npm install -g gitbook-cli
      - run: cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/ && sudo npm install graceful-fs@4.2.0 --save && cd -
      - run: gitbook install
      - run: mkdir output
      - run: gitbook epub . ./output/typescript-book-${SHA}.epub
      - name: upload epub artifact
        uses: actions/upload-artifact@v1
        with:
          name: typescript-book.epub
          path: output/typescript-book-${{ env.SHA }}.epub
      - run: gitbook pdf . ./output/typescript-book-${SHA}.pdf
      - name: upload pdf artifact
        uses: actions/upload-artifact@v1
        with:
          name: typescript-book.pdf
          path: output/typescript-book-${{ env.SHA }}.pdf
#       - run: gitbook mobi . ./output/typescript-book-${SHA}.mobi
#       - name: upload mobi artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: typescript-book.mobi
#           path: output/typescript-book-${{ env.SHA }}.mobi
